export interface CircuitMetadata {
  trackLength: string;
  lapCount: number;
  raceDistance: string;
  firstGrandPrix: number;
  corners?: number;
  drsZones?: number;
  lapRecord?: {
    time: string;
    driver: string;
    year: number;
  };
  poleRecord?: {
    time: string;
    driver: string;
    year: number;
  };
  history?: string;
  weatherSummary?: string;
}

const CIRCUIT_METADATA_DB: Record<string, CircuitMetadata> = {
  albert_park: {
    trackLength: "5.278 km",
    lapCount: 58,
    raceDistance: "306.124 km",
    firstGrandPrix: 1996,
    corners: 14,
    drsZones: 4,
    lapRecord: { time: "1:20.260", driver: "Charles Leclerc", year: 2022 },
    poleRecord: { time: "1:15.915", driver: "Max Verstappen", year: 2024 },
    history: "Albert Park Circuit has hosted the Australian Grand Prix since 1996. It is a street circuit set around Albert Park Lake, combining high-speed sections with tight chicanes.",
    weatherSummary: "Mild autumn weather with typical ocean breezes and cool temperatures.",
  },
  bahrain: {
    trackLength: "5.412 km",
    lapCount: 57,
    raceDistance: "308.238 km",
    firstGrandPrix: 2004,
    corners: 15,
    drsZones: 3,
    lapRecord: { time: "1:31.447", driver: "Pedro de la Rosa", year: 2005 },
    poleRecord: { time: "1:29.179", driver: "Lewis Hamilton", year: 2020 },
    history: "Sakhir is built in the middle of a desert, making wind and sand a unique challenge. It has hosted the Bahrain Grand Prix since 2004 and is known for its heavy braking zones.",
    weatherSummary: "Hot, dry desert weather; cooler evening conditions with strong winds.",
  },
  jeddah: {
    trackLength: "6.174 km",
    lapCount: 50,
    raceDistance: "308.450 km",
    firstGrandPrix: 2021,
    corners: 27,
    drsZones: 3,
    lapRecord: { time: "1:30.734", driver: "Lewis Hamilton", year: 2021 },
    poleRecord: { time: "1:27.472", driver: "Max Verstappen", year: 2024 },
    history: "Jeddah Corniche Circuit is the fastest street circuit on the calendar, with drivers averaging over 250 km/h between concrete walls along the Red Sea coast.",
    weatherSummary: "Warm coastal winds, humid night racing conditions.",
  },
  suzuka: {
    trackLength: "5.807 km",
    lapCount: 53,
    raceDistance: "307.471 km",
    firstGrandPrix: 1987,
    corners: 18,
    drsZones: 1,
    lapRecord: { time: "1:30.983", driver: "Lewis Hamilton", year: 2019 },
    poleRecord: { time: "1:27.064", driver: "Sebastian Vettel", year: 2006 },
    history: "Suzuka features a unique figure-eight layout, cross-over bridge, and famous high-speed sweeping sections like 130R and the Esses. It is a driver favorite.",
    weatherSummary: "Changeable spring/autumn skies with high chance of sudden showers.",
  },
  shanghai: {
    trackLength: "5.451 km",
    lapCount: 56,
    raceDistance: "305.066 km",
    firstGrandPrix: 2004,
    corners: 16,
    drsZones: 2,
    lapRecord: { time: "1:32.238", driver: "Michael Schumacher", year: 2004 },
    poleRecord: { time: "1:31.530", driver: "Sebastian Vettel", year: 2018 },
    history: "Shaped like the Chinese character 'Shang', featuring long straight runs, tight sweeping corners, and heavy traction zones.",
    weatherSummary: "Mild temperatures, overcast skies, and moderate humidity.",
  },
  miami: {
    trackLength: "5.412 km",
    lapCount: 57,
    raceDistance: "308.326 km",
    firstGrandPrix: 2022,
    corners: 19,
    drsZones: 3,
    lapRecord: { time: "1:29.708", driver: "Max Verstappen", year: 2023 },
    poleRecord: { time: "1:26.841", driver: "Charles Leclerc", year: 2022 },
    history: "Miami International Autodrome is built around the Hard Rock Stadium, offering high-speed straights alongside a tight, technical slow section under the turnpike.",
    weatherSummary: "Hot, humid tropical weather with a high chance of passing rain.",
  },
  imola: {
    trackLength: "4.909 km",
    lapCount: 63,
    raceDistance: "309.049 km",
    firstGrandPrix: 1980,
    corners: 19,
    drsZones: 1,
    lapRecord: { time: "1:15.484", driver: "Lewis Hamilton", year: 2020 },
    poleRecord: { time: "1:13.609", driver: "Valtteri Bottas", year: 2020 },
    history: "Autodromo Enzo e Dino Ferrari is an iconic old-school anti-clockwise track in Emilia-Romagna, Italy, featuring high-speed sweeps and classic curves like Acque Minerali.",
    weatherSummary: "Cool spring air with potential for localized morning showers.",
  },
  monaco: {
    trackLength: "3.337 km",
    lapCount: 78,
    raceDistance: "260.286 km",
    firstGrandPrix: 1950,
    corners: 19,
    drsZones: 1,
    lapRecord: { time: "1:12.909", driver: "Lewis Hamilton", year: 2021 },
    poleRecord: { time: "1:10.166", driver: "Lewis Hamilton", year: 2019 },
    history: "The ultimate test of precision and concentration through the narrow Monte Carlo streets. Rubbing barriers is common, and qualifying is the most crucial of the year.",
    weatherSummary: "Pleasant Mediterranean sun with occasional sea fog or humidity.",
  },
  villeneuve: {
    trackLength: "4.361 km",
    lapCount: 70,
    raceDistance: "305.270 km",
    firstGrandPrix: 1978,
    corners: 14,
    drsZones: 2,
    lapRecord: { time: "1:13.078", driver: "Valtteri Bottas", year: 2019 },
    poleRecord: { time: "1:10.240", driver: "Sebastian Vettel", year: 2018 },
    history: "Circuit Gilles-Villeneuve is a semi-permanent track on Notre Dame Island known for its heavy braking chicanes and the legendary 'Wall of Champions' at the final corner.",
    weatherSummary: "Warm summer air, but weather can shift rapidly with local thunderclouds.",
  },
  barcelona: {
    trackLength: "4.657 km",
    lapCount: 66,
    raceDistance: "307.236 km",
    firstGrandPrix: 1991,
    corners: 14,
    drsZones: 2,
    lapRecord: { time: "1:16.330", driver: "Max Verstappen", year: 2023 },
    poleRecord: { time: "1:12.272", driver: "Lando Norris", year: 2024 },
    history: "Circuit de Barcelona-Catalunya is a classic testing track, featuring high-speed sweeps and technical sectors that put aerodynamic efficiency to the test.",
    weatherSummary: "Warm, sunny, typical Spanish summer weather with gentle breezes.",
  },
  red_bull_ring: {
    trackLength: "4.318 km",
    lapCount: 71,
    raceDistance: "306.452 km",
    firstGrandPrix: 1970,
    corners: 10,
    drsZones: 3,
    lapRecord: { time: "1:05.619", driver: "Carlos Sainz", year: 2020 },
    poleRecord: { time: "1:02.939", driver: "Valtteri Bottas", year: 2020 },
    history: "Set in the Styrian hills, the Red Bull Ring is a short, fast layout consisting of four long straights connected by sweeping corners and heavy braking points.",
    weatherSummary: "Crisp alpine air, highly prone to sudden, heavy mountain storms.",
  },
  silverstone: {
    trackLength: "5.891 km",
    lapCount: 52,
    raceDistance: "306.198 km",
    firstGrandPrix: 1950,
    corners: 18,
    drsZones: 2,
    lapRecord: { time: "1:27.097", driver: "Max Verstappen", year: 2020 },
    poleRecord: { time: "1:24.303", driver: "Lewis Hamilton", year: 2020 },
    history: "The historic home of British motorsport, renowned for some of F1's most famous high-speed corners like Copse, Maggots, Becketts, and Chapel.",
    weatherSummary: "Unpredictable British weather; wind is always a significant factor.",
  },
  hungaroring: {
    trackLength: "4.381 km",
    lapCount: 70,
    raceDistance: "306.630 km",
    firstGrandPrix: 1986,
    corners: 14,
    drsZones: 1,
    lapRecord: { time: "1:16.627", driver: "Lewis Hamilton", year: 2020 },
    poleRecord: { time: "1:13.447", driver: "Lewis Hamilton", year: 2020 },
    history: "A tight, dusty, twisty layout near Budapest often compared to Monaco without walls, demanding maximum downforce and offering few overtaking points.",
    weatherSummary: "Scorching summer heat with track temperatures often exceeding 50°C.",
  },
  spa: {
    trackLength: "7.004 km",
    lapCount: 44,
    raceDistance: "308.052 km",
    firstGrandPrix: 1950,
    corners: 19,
    drsZones: 2,
    lapRecord: { time: "1:46.286", driver: "Valtteri Bottas", year: 2018 },
    poleRecord: { time: "1:41.252", driver: "Lewis Hamilton", year: 2020 },
    history: "Circuit de Spa-Francorchamps is set in the Ardennes forest, legendary for its elevation changes and iconic corners like Eau Rouge, Raidillon, and Pouhon.",
    weatherSummary: "Highly erratic weather; it can rain on one side of the track while dry on the other.",
  },
  zandvoort: {
    trackLength: "4.259 km",
    lapCount: 72,
    raceDistance: "306.587 km",
    firstGrandPrix: 1952,
    corners: 14,
    drsZones: 2,
    lapRecord: { time: "1:11.097", driver: "Lewis Hamilton", year: 2021 },
    poleRecord: { time: "1:08.885", driver: "Max Verstappen", year: 2021 },
    history: "A historic roller-coaster track with steep banking curves built directly into the sand dunes by the North Sea, making it a thrilling challenge.",
    weatherSummary: "Cool sea breezes, with sand frequently blown onto the track surface.",
  },
  monza: {
    trackLength: "5.793 km",
    lapCount: 53,
    raceDistance: "306.900 km",
    firstGrandPrix: 1950,
    corners: 11,
    drsZones: 2,
    lapRecord: { time: "1:21.046", driver: "Rubens Barrichello", year: 2004 },
    poleRecord: { time: "1:18.887", driver: "Lewis Hamilton", year: 2020 },
    history: "The Temple of Speed, featuring legendary long straights, fast corners like Curva Grande and Parabolica, and heavy braking chicanes.",
    weatherSummary: "Hot, sunny, and humid Italian summer weather.",
  },
  baku: {
    trackLength: "6.003 km",
    lapCount: 51,
    raceDistance: "306.049 km",
    firstGrandPrix: 2016,
    corners: 20,
    drsZones: 2,
    lapRecord: { time: "1:43.009", driver: "Charles Leclerc", year: 2019 },
    poleRecord: { time: "1:40.495", driver: "Valtteri Bottas", year: 2019 },
    history: "Baku City Circuit combines a tight, slow section running past the old city castle walls with a blistering 2.2 km flat-out run along the Caspian Sea.",
    weatherSummary: "Warm coastal temperatures accompanied by gusty winds.",
  },
  marina_bay: {
    trackLength: "4.940 km",
    lapCount: 62,
    raceDistance: "306.143 km",
    firstGrandPrix: 2008,
    corners: 19,
    drsZones: 3,
    lapRecord: { time: "1:35.867", driver: "Lewis Hamilton", year: 2023 },
    poleRecord: { time: "1:30.984", driver: "Carlos Sainz", year: 2023 },
    history: "A grueling night street race in Singapore. The high humidity and lack of long straights make it a physically exhausting test of endurance for drivers.",
    weatherSummary: "Intense tropical heat and humidity with high chance of evening storms.",
  },
  americas: {
    trackLength: "5.513 km",
    lapCount: 56,
    raceDistance: "308.405 km",
    firstGrandPrix: 2012,
    corners: 20,
    drsZones: 2,
    lapRecord: { time: "1:36.169", driver: "Charles Leclerc", year: 2019 },
    poleRecord: { time: "1:32.029", driver: "Valtteri Bottas", year: 2019 },
    history: "Circuit of The Americas (COTA) features a steep climb into Turn 1 and has sectors inspired by historic venues like Silverstone's Maggots/Becketts.",
    weatherSummary: "Warm autumn air with gusty and unpredictable wind conditions.",
  },
  rodriguez: {
    trackLength: "4.304 km",
    lapCount: 71,
    raceDistance: "305.354 km",
    firstGrandPrix: 1963,
    corners: 17,
    drsZones: 3,
    lapRecord: { time: "1:17.774", driver: "Valtteri Bottas", year: 2021 },
    poleRecord: { time: "1:14.759", driver: "Daniel Ricciardo", year: 2018 },
    history: "Autodromo Hermanos Rodriguez is set 2,200 meters above sea level. The thin air reduces downforce and puts high cooling demands on engines.",
    weatherSummary: "Sunny, dry, and warm afternoon temperatures with thin mountain air.",
  },
  interlagos: {
    trackLength: "4.309 km",
    lapCount: 71,
    raceDistance: "305.879 km",
    firstGrandPrix: 1973,
    corners: 15,
    drsZones: 2,
    lapRecord: { time: "1:10.540", driver: "Valtteri Bottas", year: 2018 },
    poleRecord: { time: "1:07.281", driver: "Lewis Hamilton", year: 2018 },
    history: "Autodromo Jose Carlos Pace is an anti-clockwise classic. It features a sweeping final hill and has hosted iconic championship-deciding races.",
    weatherSummary: "Warm, highly humid, and prone to rapid thunderstorms.",
  },
  vegas: {
    trackLength: "6.201 km",
    lapCount: 50,
    raceDistance: "309.958 km",
    firstGrandPrix: 2023,
    corners: 17,
    drsZones: 2,
    lapRecord: { time: "1:35.490", driver: "Oscar Piastri", year: 2023 },
    poleRecord: { time: "1:32.726", driver: "Charles Leclerc", year: 2023 },
    history: "A blistering night street circuit looping past world-famous hotels and neon landmarks on the Las Vegas Strip, featuring a 1.9 km straight.",
    weatherSummary: "Cold desert nights; track temperatures can fall under 12°C.",
  },
  losail: {
    trackLength: "5.419 km",
    lapCount: 57,
    raceDistance: "308.611 km",
    firstGrandPrix: 2021,
    corners: 16,
    drsZones: 1,
    lapRecord: { time: "1:24.319", driver: "Max Verstappen", year: 2023 },
    poleRecord: { time: "1:20.827", driver: "Max Verstappen", year: 2023 },
    history: "Lusail International Circuit is a fast, flowing track in Qatar with constant medium and high-speed corners that keep tyres under high loading.",
    weatherSummary: "Hot desert day; windy and dusty night conditions.",
  },
  yas_marina: {
    trackLength: "5.281 km",
    lapCount: 58,
    raceDistance: "306.183 km",
    firstGrandPrix: 2009,
    corners: 16,
    drsZones: 2,
    lapRecord: { time: "1:26.103", driver: "Max Verstappen", year: 2021 },
    poleRecord: { time: "1:22.109", driver: "Max Verstappen", year: 2021 },
    history: "The twilight season finale at Abu Dhabi. Designed around the marina, it features long straights and a winding hotel complex sector.",
    weatherSummary: "Dry, warm twilight air; track temperature drops as night sets in.",
  },
};

/**
 * Retrieves the verified curated metadata for a circuit, or null if unavailable.
 */
export function getCircuitMetadata(circuitId?: string): CircuitMetadata | null {
  if (!circuitId) return null;
  return CIRCUIT_METADATA_DB[circuitId] || null;
}
